[build]
command = "make build_linux_lambda"
functions = "release/linux/lambda"

[build.environment]
GO111MODULE = "on"
GO_IMPORT_PATH = "github.com/appleboy/gorush"
GO_VERSION = "1.23.8"

[[redirects]]
from = "/*"
status = 200
to = "/.netlify/functions/gorush/:splat"
